---
services:
  pihole:
    hostname: ${VIRTUAL_HOST}
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - unbound
    volumes:
      - ./config/pihole/adlists.list:/etc/pihole/adlists.list
      - ./config/pihole/pihole.toml:/etc/pihole/pihole.toml
      - ./config/dnsmasq.d/:/etc/dnsmasq.d/
      - ./data/pihole:/etc/pihole/
      - ./log/pihole/:/var/log/pihole/
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    env_file: .env
    environment:
      TZ: ETC/UTC
      PIHOLE_UID: 1000
      PIHOLE_GID: 1000
      # PIHOLE_DNS_: unbound#53
    restart: unless-stopped

  unbound:
    hostname: unbound
    container_name: unbound
    image: mvance/unbound-rpi:latest
    volumes:
      - ./config/unbound/logging.conf:/opt/unbound/etc/unbound/logging.conf
      - ./log/unbound/unbound.log:/opt/unbound/etc/unbound/unbound.log
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    restart: unless-stopped

  filebeat:
    hostname: filebeat
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.13.0-arm64
    volumes:
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./log/pihole:/var/log/pihole
      - ./log/unbound:/var/log/unbound
